# Hexo 配置
## 文档: https://hexo.io/docs/configuration.html
## 源码: https://github.com/hexojs/hexo/

# 站点
title: W1ndys小屋
subtitle: 欲戴皇冠，必承其重
description: W1ndys的博客，记录生活与技术
keywords: 博客, 生活, 技术, 记录
author: W1ndys
language: zh-CN
timezone: "Asia/Shanghai"
email: w1ndys@outlook.com

# URL
## 在此设置您的站点 URL。例如，如果您使用 GitHub Page，请将 URL 设置为 'https://username.github.io/project'
url: https://blog.w1ndys.top
## 永久链接: :year/:month/:day/:title/
permalink: posts/:abbrlink.html # 此处可以自己设置
permalink_defaults: permalink_defaults
pretty_urls:
  trailing_index: false # 设置为 false 以移除永久链接中的 'index.html'
  trailing_html: true # 设置为 false 以移除永久链接中的 '.html'

# abbrlink 配置
abbrlink:
  alg: crc32 # 计算 abbrlink 的算法。支持 crc16(默认) 和 crc32
  rep: hex # abbrlink 在 URL 中的表示。支持 dec(默认) 和 hex
  drafts: false # 是否为草稿生成 abbrlink。(false 默认)
  force: false # 启用强制模式。在此模式下，插件将忽略缓存，并为每个帖子计算 abbrlink，即使它已经有 abbrlink。(false 默认)
  writeback: true # 是否将更改写回实际的 markdown 文件。(true 默认)
  # v2 配置
  start: 1 # 启起始文章id，默认为0 ，可以自定义，比如100

# 目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - "html/**"

# 写作
new_post_name: :title.md # 新帖子的文件名
default_layout: post
titlecase: false # 将标题转换为标题大小写
external_link:
  enable: true # 在新标签页中打开外部链接
  field: site # 应用于整个站点
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""

# 首页设置
# path: 博客索引页的根路径。(默认 = '')
# per_page: 每页显示的帖子数。(0 = 禁用分页)
# order_by: 帖子排序。(默认按日期降序排序)
index_generator:
  path: ""
  per_page: 14
  order_by: -date

# 分类和标签
default_category: uncategorized
category_map:
tag_map:

# 元数据元素
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# 日期/时间格式
## Hexo 使用 Moment.js 来解析和显示日期
## 您可以自定义日期格式，如
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option 支持 'mtime', 'date', 'empty'
updated_option: "mtime"

# 分页
## 将 per_page 设置为 0 以禁用分页
per_page: 10
pagination_dir: page

# 包含/排除文件
## include:/exclude: 选项仅适用于 'source/' 文件夹
include:
exclude:
ignore:

# 扩展
## 插件: https://hexo.io/plugins/
## 主题: https://hexo.io/themes/
theme: redefine

# 部署
## 文档: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository:
    github: git@github.com:W1ndys/Blog.git
    # gitee: git@gitee.com:W1ndys/blog.git
  branch: gh-pages

mathjax:
  tags: none # 或 'ams' 或 'all'
  single_dollars: true # 启用单美元符号作为行内数学分隔符
  cjk_width: 0.9 # 相对 CJK 字符宽度
  normal_width: 0.6 # 相对正常（等宽）宽度
  append_css: true # 为每个页面添加 CSS
  every_page: false # 如果为 true，每个页面都将由 mathjax 渲染，而不管每篇文章的 Front-matter 中的 `mathjax` 设置

# hexo-generator-feed
feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: " "
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

