name: Deploy Blog
on:
  push:
    branches:
      - main  # 如果你的主分支是 main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Generate & Deploy
        run: |
          npm install hexo-deployer-git --save
          hexo generate
          hexo deploy