name: Deploy Blog
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: actions/setup-ruby@v3
        with:
          ruby-version: 3.1  # 必须与 GitHub Pages 环境一致

      - name: Install Dependencies
        run: bundle install

      - name: Build Site
        run: bundle exec jekyll build

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Jekyll 生成的静态文件目录
          keep_files: true      # 保留历史文件